travis: Enable clang
Changed configure accordingly and added Makefile.clang

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7,26 +7,38 @@
 # To prevent ugly Makefile extensions, underscore and chars following it
 # in the name XXX are automatically removed before locating relevant
 # Makefile. This is why compiler "xlc_r" has Makefile extension "xlc".
-# This can be disabled if neccessary.
+# This can be disabled if necessary.
 #
+set -x
 
-CCS="xlc_r gcc"
-
-#
-# Look for supported compilers
-#
-for c in $CCS; do
-	if CCPATH=`which $c 2>&1` && [ -z "${CCPATH%%/*}" ]; then
-		CC="$c"
-		break
+if [ -n "$CC" ]; then
+	# If compiler is specified look for the path
+	CCPATH=$(which $CC 2>&1)
+	if [ -n "${CCPATH%%/*}" ]; then
+		echo "Unable to find $CC, will search for a compatible compiler ..."
+		CC=
 	fi
-done
+fi
+
+if [ -z "$CC" ]; then
+	CCS="xlc_r gcc clang"
+
+	#
+	# Look for supported compilers
+	#
+	for c in $CCS; do
+		if CCPATH=`which $c 2>&1` && [ -z "${CCPATH%%/*}" ]; then
+			CC="$c"
+			break
+		fi
+	done
+fi
 
 #
 # Make a link to a proper Makefile.*
 #
 if [ -z "$CC" ]; then
-	echo "Unable to find GNU GCC or IBM XL C/C++. Fix your PATH!"
+	echo "Unable to find GNU GCC, IBM XL C/C++ or clang. Fix your PATH!"
 	exit 1
 else
 	echo "Using $CCPATH to compile Cntlm"
@@ -40,13 +52,18 @@ else
 			fi
 			;;
 		*)
-			# backup default GCC Makefile and create a link to other
-			if [ -f Makefile ]; then
-				mv Makefile Makefile.gcc
-			fi
-
 			EXT=`echo "$CC" | sed 's/_.*//'`
-			ln -s Makefile.$EXT Makefile
+			if [ ! -f "Makefile.$EXT" ]; then
+				echo "There must be a file 'Makefile.$EXT' to compile it with $CC"
+				exit 1
+			else
+				# backup default GCC Makefile and create a link to other
+				if [ -f Makefile ]; then
+					mv Makefile Makefile.gcc
+				fi
+
+				ln -s Makefile.$EXT Makefile
+			fi
 			;;
 	esac
 fi
